# Generated by Django 3.1.3 on 2022-03-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functioncreate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='functioncreate',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='functioncreate',
            name='function_body',
            field=models.FileField(upload_to='upload/%Y%m%d/'),
        ),
    ]
