# Generated by Django 3.1.3 on 2022-03-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functioncreate', '0002_auto_20220317_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functioncreate',
            name='function_body',
            field=models.FileField(null=True, upload_to='upload/%Y%m%d/'),
        ),
    ]
